/* msgbox_service_impl.h

 Generated by phxrpc_pb2service from msgbox.proto

*/

#pragma once

#include "msgbox.pb.h"
#include "phxrpc_msgbox_service.h"

class MsgBoxServerConfig;

typedef struct tagServiceArgs {
    MsgBoxServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class MsgBoxServiceImpl : public MsgBoxService
{
public:
    MsgBoxServiceImpl( ServiceArgs_t & args );
    virtual ~MsgBoxServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Add( const msgbox::MsgIndex & req,
        msgbox::AddMsgResp * resp );

    virtual int GetBySeq( const msgbox::GetBySeqReq & req,
        msgbox::MsgIndexList * resp );

    virtual int GetAll( const google::protobuf::StringValue & req,
        msgbox::MsgIndexList * resp );

private:
    ServiceArgs_t & args_;
};

