/* msgbox_server_config.cpp

 Generated by phxrpc_pb2server from msgbox.proto

*/

#include "msgbox.pb.h"
#include "msgbox_server_config.h"

MsgBoxServerConfig :: MsgBoxServerConfig()
{
}

MsgBoxServerConfig :: ~MsgBoxServerConfig()
{
}

bool MsgBoxServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
msgbox::MsgIndex::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

const phxrpc::HshaServerConfig & MsgBoxServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
