/* msgbox_tool_impl.h

 Generated by phxrpc_pb2tool from msgbox.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_msgbox_tool.h"
namespace phxrpc {
    class OptMap;
}

class MsgBoxToolImpl : public MsgBoxTool
{
public:
    MsgBoxToolImpl();
    virtual ~MsgBoxToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int Add( phxrpc::OptMap & opt_map );

    virtual int GetBySeq( phxrpc::OptMap & opt_map );

    virtual int GetAll( phxrpc::OptMap & opt_map );

};

