/* msgbox_client.cpp

 Generated by phxrpc_pb2client from msgbox.proto

*/

#include <iostream>
#include <memory>
#include <stdlib.h>
#include <mutex>

#include "msgbox_client.h"
#include "phxrpc_msgbox_stub.h"

#include "phxrpc/rpc.h"

static phxrpc::ClientConfig global_msgboxclient_config_;
static phxrpc::ClientMonitorPtr global_msgboxclient_monitor_;

bool MsgBoxClient :: Init( const char * config_file )
{
    return global_msgboxclient_config_.Read( config_file );
}

const char * MsgBoxClient :: GetPackageName() {
    const char * ret = global_msgboxclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "msgbox";
    }
    return ret;
}

MsgBoxClient :: MsgBoxClient()
{
    static std::mutex monitor_mutex;
    if ( !global_msgboxclient_monitor_.get() ) { 
        monitor_mutex.lock();
        if ( !global_msgboxclient_monitor_.get() ) {
            global_msgboxclient_monitor_ = phxrpc::MonitorFactory::GetFactory()
                ->CreateClientMonitor( GetPackageName() );
        }
        global_msgboxclient_config_.SetClientMonitor( global_msgboxclient_monitor_ );
        monitor_mutex.unlock();
    }
}

MsgBoxClient :: ~MsgBoxClient()
{
}

int MsgBoxClient :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_msgboxclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_msgboxclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_msgboxclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_msgboxclient_config_.GetSocketTimeoutMS());

            MsgBoxStub stub(socket, *(global_msgboxclient_monitor_.get()));
            return stub.PHXEcho(req, resp);
        } 
    }

    return -1;
}

int MsgBoxClient :: PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    int ret = -1; 
    size_t echo_server_count = 2;
    uthread_begin;
    for (size_t i = 0; i < echo_server_count; i++) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t * ep = global_msgboxclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if(phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                            global_msgboxclient_config_.GetConnectTimeoutMS(), *(global_msgboxclient_monitor_.get()))) { 
                    socket.SetTimeout(global_msgboxclient_config_.GetSocketTimeoutMS());
                    MsgBoxStub stub(socket, *(global_msgboxclient_monitor_.get()));
                    int this_ret = stub.PHXEcho(req, resp);
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }   
                }   
            }
        };  
    }   
    uthread_end;
    return ret;
}

int MsgBoxClient :: Add( const msgbox::MsgIndex & req,
        msgbox::AddMsgResp * resp )
{
    const phxrpc::Endpoint_t * ep = global_msgboxclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_msgboxclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_msgboxclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_msgboxclient_config_.GetSocketTimeoutMS());

            MsgBoxStub stub(socket, *(global_msgboxclient_monitor_.get()));
            return stub.Add(req, resp);
        } 
    }

    return -1;
}

int MsgBoxClient :: GetBySeq( const msgbox::GetBySeqReq & req,
        msgbox::MsgIndexList * resp )
{
    const phxrpc::Endpoint_t * ep = global_msgboxclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_msgboxclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_msgboxclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_msgboxclient_config_.GetSocketTimeoutMS());

            MsgBoxStub stub(socket, *(global_msgboxclient_monitor_.get()));
            return stub.GetBySeq(req, resp);
        } 
    }

    return -1;
}

int MsgBoxClient :: GetAll( const google::protobuf::StringValue & req,
        msgbox::MsgIndexList * resp )
{
    const phxrpc::Endpoint_t * ep = global_msgboxclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_msgboxclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_msgboxclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_msgboxclient_config_.GetSocketTimeoutMS());

            MsgBoxStub stub(socket, *(global_msgboxclient_monitor_.get()));
            return stub.GetAll(req, resp);
        } 
    }

    return -1;
}


