/* account_tool_impl.h

 Generated by phxrpc_pb2tool from account.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_account_tool.h"
namespace phxrpc {
    class OptMap;
}

class AccountToolImpl : public AccountTool
{
public:
    AccountToolImpl();
    virtual ~AccountToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int Add( phxrpc::OptMap & opt_map );

    virtual int Get( phxrpc::OptMap & opt_map );

    virtual int Auth( phxrpc::OptMap & opt_map );

};

