/* account_service_impl.cpp

 Generated by phxrpc_pb2service from account.proto

*/

#include "account_service_impl.h"
#include "account_server_config.h"
#include "account.pb.h"
#include "phxrpc/file.h"

#include "common/redis_client_factory.h"
#include "account_dao.h"

AccountServiceImpl :: AccountServiceImpl( ServiceArgs_t & args )
    : args_( args )
{
}

AccountServiceImpl :: ~AccountServiceImpl()
{
}

int AccountServiceImpl :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    resp->set_value( req.value() );
    return 0;
}

int AccountServiceImpl :: Set( const account::User & req,
        google::protobuf::Empty * resp )
{
    AccountDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Set( req );;
}

int AccountServiceImpl :: SetPwd( const account::PwdReq & req,
        google::protobuf::Empty * resp )
{
    AccountDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.SetPwd( req );
}

int AccountServiceImpl :: Get( const google::protobuf::StringValue & req,
        account::User * resp )
{
    AccountDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Get( req.value().c_str(), resp );
}

int AccountServiceImpl :: Auth( const account::PwdReq & req,
        google::protobuf::Empty * resp )
{
    AccountDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Auth( req );
}


