/* account_client.h

 Generated by phxrpc_pb2client from account.proto

*/

#pragma once

#include <string>
#include "account.pb.h"
#include "phxrpc/rpc.h"

class AccountClient
{
public:
    AccountClient();
    ~AccountClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Set( const account::User & req,
        google::protobuf::Empty * resp );

    int SetPwd( const account::PwdReq & req,
        google::protobuf::Empty * resp );

    int Get( const google::protobuf::StringValue & req,
        account::User * resp );

    int Auth( const account::PwdReq & req,
        google::protobuf::Empty * resp );


private:
    std::string package_name_;
    phxrpc::ClientConfig * config_;
};
