/* account_server_config.cpp

 Generated by phxrpc_pb2server from account.proto

*/

#include "account.pb.h"
#include "account_server_config.h"

AccountServerConfig :: AccountServerConfig()
{
}

AccountServerConfig :: ~AccountServerConfig()
{
}

bool AccountServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
account::User::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & AccountServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
