/* account_tool_impl.cpp

 Generated by phxrpc_pb2tool from account.proto

*/

#include "account_tool_impl.h"
#include "account_client.h"

#include "phxrpc/file.h"

using namespace phxrpc;

AccountToolImpl:: AccountToolImpl()
{
}

AccountToolImpl:: ~AccountToolImpl()
{
}

int AccountToolImpl :: PHXEcho( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if( NULL == opt_map.Get( 's' ) ) return -1;

    req.set_value( opt_map.Get( 's' ) );

    AccountClient client;
    int ret = client.PHXEcho( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AccountToolImpl :: Add( phxrpc::OptMap & opt_map )
{
    account::User req;
    google::protobuf::Empty resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.set_createtime( time( NULL ) );

    AccountClient client;
    int ret = client.Add( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AccountToolImpl :: SetPwd( phxrpc::OptMap & opt_map )
{
    account::PwdReq req;
    google::protobuf::Empty resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) || NULL == opt_map.Get( 'p' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.set_pwd_md5( opt_map.Get( 'p' ) );

    AccountClient client;
    int ret = client.SetPwd( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AccountToolImpl :: Get( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    account::User resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) ) return -1;

    req.set_value( opt_map.Get( 'u' ) );

    AccountClient client;
    int ret = client.Get( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AccountToolImpl :: Auth( phxrpc::OptMap & opt_map )
{
    account::PwdReq req;
    google::protobuf::Empty resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) || NULL == opt_map.Get( 'p' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.set_pwd_md5( opt_map.Get( 'p' ) );

    AccountClient client;
    int ret = client.Auth( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

