/* addrbook_server_config.cpp

 Generated by phxrpc_pb2server from addrbook.proto

*/

#include "addrbook.pb.h"
#include "addrbook_server_config.h"

AddrbookServerConfig :: AddrbookServerConfig()
{
}

AddrbookServerConfig :: ~AddrbookServerConfig()
{
}

bool AddrbookServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
            addrbook::ContactReq::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

const phxrpc::HshaServerConfig & AddrbookServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
