/* addrbook_client.h

 Generated by phxrpc_pb2client from addrbook.proto

*/

#pragma once

#include "addrbook.pb.h"
#include "phxrpc/rpc.h"

class AddrbookClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    AddrbookClient();
    ~AddrbookClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Add( const addrbook::ContactReq & req,
        google::protobuf::Empty * resp );

    int GetAll( const google::protobuf::StringValue & req,
        addrbook::ContactList * resp );

    int GetOne( const addrbook::GetOneReq & req,
        addrbook::Contact * resp );


};
