/* addrbook_client.h

 Generated by phxrpc_pb2client from addrbook.proto

*/

#pragma once

#include <string>
#include "addrbook.pb.h"
#include "phxrpc/rpc.h"

class AddrbookClient
{
public:
    AddrbookClient();
    ~AddrbookClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Set( const addrbook::ContactReq & req,
        google::protobuf::Empty * resp );

    int GetAll( const google::protobuf::StringValue & req,
        addrbook::ContactList * resp );

    int GetOne( const addrbook::GetOneReq & req,
        addrbook::Contact * resp );

    int GetBySeq( const addrbook::GetBySeqReq & req,
        addrbook::ContactList * resp );


private:
    std::string package_name_;
    phxrpc::ClientConfig * config_;
};
