/* addrbook_tool_impl.cpp

 Generated by phxrpc_pb2tool from addrbook.proto

*/

#include "addrbook_tool_impl.h"
#include "addrbook_client.h"

#include "phxrpc/file.h"

using namespace phxrpc;

AddrbookToolImpl:: AddrbookToolImpl()
{
}

AddrbookToolImpl:: ~AddrbookToolImpl()
{
}

int AddrbookToolImpl :: PHXEcho( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if( NULL == opt_map.Get( 's' ) ) return -1;

    req.set_value( opt_map.Get( 's' ) );

    AddrbookClient client;
    int ret = client.PHXEcho( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AddrbookToolImpl :: Set( phxrpc::OptMap & opt_map )
{
    addrbook::ContactReq req;
    google::protobuf::Empty resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) || NULL == opt_map.Get( 't' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.mutable_contact()->set_username( opt_map.Get( 't' ) );
    req.mutable_contact()->set_remark( opt_map.Get( 't' ) );

    AddrbookClient client;
    int ret = client.Set( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AddrbookToolImpl :: GetAll( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    addrbook::ContactList resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) ) return -1;

    req.set_value( opt_map.Get( 'u' ) );

    AddrbookClient client;
    int ret = client.GetAll( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AddrbookToolImpl :: GetOne( phxrpc::OptMap & opt_map )
{
    addrbook::GetOneReq req;
    addrbook::Contact resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) || NULL == opt_map.Get( 't' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.set_contact( opt_map.Get( 't' ) );

    AddrbookClient client;
    int ret = client.GetOne( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int AddrbookToolImpl :: GetBySeq( phxrpc::OptMap & opt_map )
{
    addrbook::GetBySeqReq req;
    addrbook::ContactList resp;

    // fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) || NULL == opt_map.Get( 's' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.set_seq( atoi( opt_map.Get( 's' ) ) );

    AddrbookClient client;
    int ret = client.GetBySeq( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

