/* addrbook_service_impl.h

 Generated by phxrpc_pb2service from addrbook.proto

*/

#pragma once

#include "addrbook.pb.h"
#include "phxrpc_addrbook_service.h"

class AddrbookServerConfig;
class RedisClientFactory;

typedef struct tagServiceArgs {
    AddrbookServerConfig * config;
    //You can add other arguments here and initiate in main().
    RedisClientFactory * factory;
}ServiceArgs_t;

class AddrbookServiceImpl : public AddrbookService
{
public:
    AddrbookServiceImpl( ServiceArgs_t & args );
    virtual ~AddrbookServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Add( const addrbook::ContactReq & req,
        google::protobuf::Empty * resp );

    virtual int GetAll( const google::protobuf::StringValue & req,
        addrbook::ContactList * resp );

    virtual int GetOne( const addrbook::GetOneReq & req,
        addrbook::Contact * resp );

private:
    ServiceArgs_t & args_;
};

