/* logic_client.h

 Generated by phxrpc_pb2client from logic.proto

*/

#pragma once

#include "logic.pb.h"
#include "phxrpc/rpc.h"

class LogicClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    LogicClient();
    ~LogicClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Auth( const logic::MiniRequest & req,
        logic::MiniResponse * resp );

    int Sync( const logic::MiniRequest & req,
        logic::MiniResponse * resp );

    int SendMsg( const logic::MiniRequest & req,
        logic::MiniResponse * resp );


};
