/* minichat_client.h

 Generated by phxrpc_pb2client from minichat.proto

*/

#pragma once

#include "minichat.pb.h"
#include "phxrpc/rpc.h"

class MiniChatClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    MiniChatClient();
    ~MiniChatClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Auth( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp );

    int Sync( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp );

    int SendMsg( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp );


};
