/* minichat_tool_impl.h

 Generated by phxrpc_pb2tool from minichat.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_minichat_tool.h"
namespace phxrpc {
    class OptMap;
}

class MiniChatToolImpl : public MiniChatTool
{
public:
    MiniChatToolImpl();
    virtual ~MiniChatToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int Auth( phxrpc::OptMap & opt_map );

    virtual int Sync( phxrpc::OptMap & opt_map );

    virtual int SendMsg( phxrpc::OptMap & opt_map );

};

