/* minichat_service_impl.h

 Generated by phxrpc_pb2service from minichat.proto

*/

#pragma once

#include "minichat.pb.h"
#include "phxrpc_minichat_service.h"

class MiniChatServerConfig;

typedef struct tagServiceArgs {
    MiniChatServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class MiniChatServiceImpl : public MiniChatService
{
public:
    MiniChatServiceImpl( ServiceArgs_t * app_args );
    virtual ~MiniChatServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Auth( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp );

    virtual int Sync( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp );

    virtual int SendMsg( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp );

private:
    const MiniChatServerConfig & config_;
};

