/* minichat_server_config.cpp

 Generated by phxrpc_pb2server from minichat.proto

*/

#include "minichat.pb.h"
#include "minichat_server_config.h"

MiniChatServerConfig :: MiniChatServerConfig()
{
}

MiniChatServerConfig :: ~MiniChatServerConfig()
{
}

bool MiniChatServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
minichat::MiniRequest::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

const phxrpc::HshaServerConfig & MiniChatServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
