/* minichat_client.cpp

 Generated by phxrpc_pb2client from minichat.proto

*/

#include <iostream>
#include <memory>
#include <stdlib.h>
#include <mutex>

#include "minichat_client.h"
#include "phxrpc_minichat_stub.h"

#include "phxrpc/rpc.h"

static phxrpc::ClientConfig global_minichatclient_config_;
static phxrpc::ClientMonitorPtr global_minichatclient_monitor_;

bool MiniChatClient :: Init( const char * config_file )
{
    return global_minichatclient_config_.Read( config_file );
}

const char * MiniChatClient :: GetPackageName() {
    const char * ret = global_minichatclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "minichat";
    }
    return ret;
}

MiniChatClient :: MiniChatClient()
{
    static std::mutex monitor_mutex;
    if ( !global_minichatclient_monitor_.get() ) { 
        monitor_mutex.lock();
        if ( !global_minichatclient_monitor_.get() ) {
            global_minichatclient_monitor_ = phxrpc::MonitorFactory::GetFactory()
                ->CreateClientMonitor( GetPackageName() );
        }
        global_minichatclient_config_.SetClientMonitor( global_minichatclient_monitor_ );
        monitor_mutex.unlock();
    }
}

MiniChatClient :: ~MiniChatClient()
{
}

int MiniChatClient :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_minichatclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_minichatclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_minichatclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_minichatclient_config_.GetSocketTimeoutMS());

            MiniChatStub stub(socket, *(global_minichatclient_monitor_.get()));
            return stub.PHXEcho(req, resp);
        } 
    }

    return -1;
}

int MiniChatClient :: PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    int ret = -1; 
    size_t echo_server_count = 2;
    uthread_begin;
    for (size_t i = 0; i < echo_server_count; i++) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t * ep = global_minichatclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if(phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                            global_minichatclient_config_.GetConnectTimeoutMS(), *(global_minichatclient_monitor_.get()))) { 
                    socket.SetTimeout(global_minichatclient_config_.GetSocketTimeoutMS());
                    MiniChatStub stub(socket, *(global_minichatclient_monitor_.get()));
                    int this_ret = stub.PHXEcho(req, resp);
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }   
                }   
            }
        };  
    }   
    uthread_end;
    return ret;
}

int MiniChatClient :: Auth( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp )
{
    const phxrpc::Endpoint_t * ep = global_minichatclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_minichatclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_minichatclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_minichatclient_config_.GetSocketTimeoutMS());

            MiniChatStub stub(socket, *(global_minichatclient_monitor_.get()));
            return stub.Auth(req, resp);
        } 
    }

    return -1;
}

int MiniChatClient :: Sync( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp )
{
    const phxrpc::Endpoint_t * ep = global_minichatclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_minichatclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_minichatclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_minichatclient_config_.GetSocketTimeoutMS());

            MiniChatStub stub(socket, *(global_minichatclient_monitor_.get()));
            return stub.Sync(req, resp);
        } 
    }

    return -1;
}

int MiniChatClient :: SendMsg( const minichat::MiniRequest & req,
        minichat::MiniResponse * resp )
{
    const phxrpc::Endpoint_t * ep = global_minichatclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_minichatclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_minichatclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_minichatclient_config_.GetSocketTimeoutMS());

            MiniChatStub stub(socket, *(global_minichatclient_monitor_.get()));
            return stub.SendMsg(req, resp);
        } 
    }

    return -1;
}


