/* presence_tool_impl.h

 Generated by phxrpc_pb2tool from presence.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_presence_tool.h"
namespace phxrpc {
    class OptMap;
}

class PresenceToolImpl : public PresenceTool
{
public:
    PresenceToolImpl();
    virtual ~PresenceToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int Create( phxrpc::OptMap & opt_map );

    virtual int Get( phxrpc::OptMap & opt_map );

    virtual int Remove( phxrpc::OptMap & opt_map );

};

