/* presence_client.cpp

 Generated by phxrpc_pb2client from presence.proto

*/

#include <iostream>
#include <memory>
#include <stdlib.h>
#include <mutex>

#include "presence_client.h"
#include "phxrpc_presence_stub.h"

#include "phxrpc/rpc.h"

static phxrpc::ClientConfig global_presenceclient_config_;
static phxrpc::ClientMonitorPtr global_presenceclient_monitor_;

bool PresenceClient :: Init( const char * config_file )
{
    return global_presenceclient_config_.Read( config_file );
}

const char * PresenceClient :: GetPackageName() {
    const char * ret = global_presenceclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "presence";
    }
    return ret;
}

PresenceClient :: PresenceClient()
{
    static std::mutex monitor_mutex;
    if ( !global_presenceclient_monitor_.get() ) { 
        monitor_mutex.lock();
        if ( !global_presenceclient_monitor_.get() ) {
            global_presenceclient_monitor_ = phxrpc::MonitorFactory::GetFactory()
                ->CreateClientMonitor( GetPackageName() );
        }
        global_presenceclient_config_.SetClientMonitor( global_presenceclient_monitor_ );
        monitor_mutex.unlock();
    }
}

PresenceClient :: ~PresenceClient()
{
}

int PresenceClient :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_presenceclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_presenceclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_presenceclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_presenceclient_config_.GetSocketTimeoutMS());

            PresenceStub stub(socket, *(global_presenceclient_monitor_.get()));
            return stub.PHXEcho(req, resp);
        } 
    }

    return -1;
}

int PresenceClient :: PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    int ret = -1; 
    size_t echo_server_count = 2;
    uthread_begin;
    for (size_t i = 0; i < echo_server_count; i++) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t * ep = global_presenceclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if(phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                            global_presenceclient_config_.GetConnectTimeoutMS(), *(global_presenceclient_monitor_.get()))) { 
                    socket.SetTimeout(global_presenceclient_config_.GetSocketTimeoutMS());
                    PresenceStub stub(socket, *(global_presenceclient_monitor_.get()));
                    int this_ret = stub.PHXEcho(req, resp);
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }   
                }   
            }
        };  
    }   
    uthread_end;
    return ret;
}

int PresenceClient :: Create( const google::protobuf::StringValue & req,
        presence::Session * resp )
{
    const phxrpc::Endpoint_t * ep = global_presenceclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_presenceclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_presenceclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_presenceclient_config_.GetSocketTimeoutMS());

            PresenceStub stub(socket, *(global_presenceclient_monitor_.get()));
            return stub.Create(req, resp);
        } 
    }

    return -1;
}

int PresenceClient :: Get( const google::protobuf::StringValue & req,
        presence::Session * resp )
{
    const phxrpc::Endpoint_t * ep = global_presenceclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_presenceclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_presenceclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_presenceclient_config_.GetSocketTimeoutMS());

            PresenceStub stub(socket, *(global_presenceclient_monitor_.get()));
            return stub.Get(req, resp);
        } 
    }

    return -1;
}

int PresenceClient :: Remove( const google::protobuf::StringValue & req,
        presence::Session * resp )
{
    const phxrpc::Endpoint_t * ep = global_presenceclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_presenceclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_presenceclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_presenceclient_config_.GetSocketTimeoutMS());

            PresenceStub stub(socket, *(global_presenceclient_monitor_.get()));
            return stub.Remove(req, resp);
        } 
    }

    return -1;
}


