/* presence_server_config.h

 Generated by phxrpc_pb2server from presence.proto

*/

#pragma once

#include "phxrpc/rpc.h"

class PresenceServerConfig
{
public:
    PresenceServerConfig();

    ~PresenceServerConfig();

    bool Read( const char * config_file );

    const phxrpc::HshaServerConfig & GetHshaServerConfig();

private:
    phxrpc::HshaServerConfig ep_server_config_;
};
