/* presence_service_impl.cpp

 Generated by phxrpc_pb2service from presence.proto

*/

#include "presence_service_impl.h"
#include "presence_server_config.h"
#include "presence.pb.h"
#include "phxrpc/file.h"

#include "presence_dao.h"

#include "common/redis_client_factory.h"

PresenceServiceImpl :: PresenceServiceImpl( ServiceArgs_t & args )
    : args_( args )
{
}

PresenceServiceImpl :: ~PresenceServiceImpl()
{
}

int PresenceServiceImpl :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    resp->set_value( req.value() );
    return 0;
}

int PresenceServiceImpl :: Create( const google::protobuf::StringValue & req,
        presence::Session * resp )
{
    PresenceDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Create( req.value().c_str(), resp );
}

int PresenceServiceImpl :: Get( const google::protobuf::StringValue & req,
        presence::Session * resp )
{
    PresenceDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Get( req.value().c_str(), resp );
}

int PresenceServiceImpl :: Remove( const google::protobuf::StringValue & req,
        presence::Session * resp )
{
    PresenceDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Remove( req.value().c_str(), resp );
}

