/* presence_service_impl.h

 Generated by phxrpc_pb2service from presence.proto

*/

#pragma once

#include "presence.pb.h"
#include "phxrpc_presence_service.h"

class PresenceServerConfig;

class RedisClientFactory;

typedef struct tagServiceArgs {
    PresenceServerConfig * config;
    //You can add other arguments here and initiate in main().
    RedisClientFactory * factory;
}ServiceArgs_t;

class PresenceServiceImpl : public PresenceService
{
public:
    PresenceServiceImpl( ServiceArgs_t & args );
    virtual ~PresenceServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Create( const google::protobuf::StringValue & req,
        presence::Session * resp );

    virtual int Get( const google::protobuf::StringValue & req,
        presence::Session * resp );

    virtual int Remove( const google::protobuf::StringValue & req,
        presence::Session * resp );

private:
    ServiceArgs_t & args_;
};

