/* presence_server_config.cpp

 Generated by phxrpc_pb2server from presence.proto

*/

#include "presence.pb.h"
#include "presence_server_config.h"

PresenceServerConfig :: PresenceServerConfig()
{
}

PresenceServerConfig :: ~PresenceServerConfig()
{
}

bool PresenceServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
presence::Session::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & PresenceServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
