/* profile_service_impl.h

 Generated by phxrpc_pb2service from profile.proto

*/

#pragma once

#include "profile.pb.h"
#include "phxrpc_profile_service.h"

class ProfileServerConfig;

typedef struct tagServiceArgs {
    ProfileServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class ProfileServiceImpl : public ProfileService
{
public:
    ProfileServiceImpl( ServiceArgs_t & args );
    virtual ~ProfileServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Set( const profile::Setting & req,
        google::protobuf::Empty * resp );

    virtual int Get( const google::protobuf::StringValue & req,
        profile::Setting * resp );

private:
    ServiceArgs_t & args_;
};

