/* profile_tool_impl.cpp

 Generated by phxrpc_pb2tool from profile.proto

*/

#include "profile_tool_impl.h"
#include "profile_client.h"

#include "phxrpc/file.h"

using namespace phxrpc;

ProfileToolImpl:: ProfileToolImpl()
{
}

ProfileToolImpl:: ~ProfileToolImpl()
{
}

int ProfileToolImpl :: PHXEcho( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    google::protobuf::StringValue resp;

    if( NULL == opt_map.Get( 's' ) ) return -1;

    req.set_value( opt_map.Get( 's' ) );

    ProfileClient client;
    int ret = client.PHXEcho( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int ProfileToolImpl :: Set( phxrpc::OptMap & opt_map )
{
    profile::Setting req;
    google::protobuf::Empty resp;

    //TODO: fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) || NULL == opt_map.Get( 'a' ) ) return -1;

    req.set_username( opt_map.Get( 'u' ) );
    req.set_avatar( opt_map.Get( 'a' ) );
    req.set_push_without_detail( 1 );

    ProfileClient client;
    int ret = client.Set( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

int ProfileToolImpl :: Get( phxrpc::OptMap & opt_map )
{
    google::protobuf::StringValue req;
    profile::Setting resp;

    //TODO: fill req from opt_map

    if( NULL == opt_map.Get( 'u' ) ) return -1;

    req.set_value( opt_map.Get( 'u' ) );

    ProfileClient client;
    int ret = client.Get( req, &resp );
    printf( "%s return %d\n", __func__, ret );
    printf( "resp: {\n%s}\n", resp.DebugString().c_str() );

    return ret;
}

