/* profile_client.h

 Generated by phxrpc_pb2client from profile.proto

*/

#pragma once

#include <string>
#include "profile.pb.h"
#include "phxrpc/rpc.h"

class ProfileClient
{
public:
    ProfileClient();
    ~ProfileClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Set( const profile::Setting & req,
        google::protobuf::Empty * resp );

    int Get( const google::protobuf::StringValue & req,
        profile::Setting * resp );


private:
    std::string package_name_;
    phxrpc::ClientConfig * config_;
};
