/* cert_server_config.h

 Generated by phxrpc_pb2server from cert.proto

*/

#pragma once

#include "phxrpc/rpc.h"

class CertServerConfig
{
public:
    CertServerConfig();

    ~CertServerConfig();

    bool Read( const char * config_file );

    const phxrpc::HshaServerConfig & GetHshaServerConfig();

private:
    phxrpc::HshaServerConfig ep_server_config_;
};
