/* cert_service_impl.cpp

 Generated by phxrpc_pb2service from cert.proto

*/

#include "cert_service_impl.h"
#include "cert_server_config.h"
#include "cert.pb.h"
#include "phxrpc/file.h"

#include "cert_codec.h"

CertServiceImpl :: CertServiceImpl( ServiceArgs_t * app_args )
    : config_( *(app_args->config) )
{
}

CertServiceImpl :: ~CertServiceImpl()
{
}

int CertServiceImpl :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    resp->set_value( req.value() );
    return 0;
}

int CertServiceImpl :: RSADecrypt( const cert::EncBuff & req,
        google::protobuf::BytesValue * resp )
{
    return CertCodec::GetDefault()->RSADecrypt( req, resp );
}

int CertServiceImpl :: AESDecrypt( const cert::EncBuff & req,
        google::protobuf::BytesValue * resp )
{
    return -1;
}


