/* cert_server_config.cpp

 Generated by phxrpc_pb2server from cert.proto

*/

#include "cert.pb.h"
#include "cert_server_config.h"

CertServerConfig :: CertServerConfig()
{
}

CertServerConfig :: ~CertServerConfig()
{
}

bool CertServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
            cert::CodecBuff::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & CertServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
