/* cert_tool_impl.h

 Generated by phxrpc_pb2tool from cert.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_cert_tool.h"
namespace phxrpc {
    class OptMap;
}

class CertToolImpl : public CertTool
{
public:
    CertToolImpl();
    virtual ~CertToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int RSADecrypt( phxrpc::OptMap & opt_map );

    virtual int AESEncrypt( phxrpc::OptMap & opt_map );

    virtual int AESDecrypt( phxrpc::OptMap & opt_map );

};

