/* cert_client.cpp

 Generated by phxrpc_pb2client from cert.proto

*/

#include <iostream>
#include <memory>
#include <stdlib.h>
#include <mutex>

#include "cert_client.h"
#include "phxrpc_cert_stub.h"

#include "phxrpc/rpc.h"

static phxrpc::ClientConfig global_certclient_config_;
static phxrpc::ClientMonitorPtr global_certclient_monitor_;

bool CertClient :: Init( const char * config_file )
{
    return global_certclient_config_.Read( config_file );
}

const char * CertClient :: GetPackageName() {
    const char * ret = global_certclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "cert";
    }
    return ret;
}

CertClient :: CertClient()
{
    static std::mutex monitor_mutex;
    if ( !global_certclient_monitor_.get() ) { 
        monitor_mutex.lock();
        if ( !global_certclient_monitor_.get() ) {
            global_certclient_monitor_ = phxrpc::MonitorFactory::GetFactory()
                ->CreateClientMonitor( GetPackageName() );
        }
        global_certclient_config_.SetClientMonitor( global_certclient_monitor_ );
        monitor_mutex.unlock();
    }
}

CertClient :: ~CertClient()
{
}

int CertClient :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_certclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_certclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_certclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_certclient_config_.GetSocketTimeoutMS());

            CertStub stub(socket, *(global_certclient_monitor_.get()));
            return stub.PHXEcho(req, resp);
        } 
    }

    return -1;
}

int CertClient :: PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    int ret = -1; 
    size_t echo_server_count = 2;
    uthread_begin;
    for (size_t i = 0; i < echo_server_count; i++) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t * ep = global_certclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if(phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                            global_certclient_config_.GetConnectTimeoutMS(), *(global_certclient_monitor_.get()))) { 
                    socket.SetTimeout(global_certclient_config_.GetSocketTimeoutMS());
                    CertStub stub(socket, *(global_certclient_monitor_.get()));
                    int this_ret = stub.PHXEcho(req, resp);
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }   
                }   
            }
        };  
    }   
    uthread_end;
    return ret;
}

int CertClient :: RSADecrypt( const cert::CodecBuff & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_certclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_certclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_certclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_certclient_config_.GetSocketTimeoutMS());

            CertStub stub(socket, *(global_certclient_monitor_.get()));
            return stub.RSADecrypt(req, resp);
        } 
    }

    return -1;
}

int CertClient :: AESEncrypt( const cert::CodecBuff & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_certclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_certclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_certclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_certclient_config_.GetSocketTimeoutMS());

            CertStub stub(socket, *(global_certclient_monitor_.get()));
            return stub.AESEncrypt(req, resp);
        } 
    }

    return -1;
}

int CertClient :: AESDecrypt( const cert::CodecBuff & req,
        google::protobuf::BytesValue * resp )
{
    const phxrpc::Endpoint_t * ep = global_certclient_config_.GetRandom();

    if(ep != nullptr) {
        phxrpc::BlockTcpStream socket;
        bool open_ret = phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                    global_certclient_config_.GetConnectTimeoutMS(), NULL, 0, 
                    *(global_certclient_monitor_.get()));
        if ( open_ret ) {
            socket.SetTimeout(global_certclient_config_.GetSocketTimeoutMS());

            CertStub stub(socket, *(global_certclient_monitor_.get()));
            return stub.AESDecrypt(req, resp);
        } 
    }

    return -1;
}


