/* cert_service_impl.h

 Generated by phxrpc_pb2service from cert.proto

*/

#pragma once

#include "cert.pb.h"
#include "phxrpc_cert_service.h"

class CertServerConfig;

typedef struct tagServiceArgs {
    CertServerConfig * config;
    //You can add other arguments here and initiate in main().
}ServiceArgs_t;

class CertServiceImpl : public CertService
{
public:
    CertServiceImpl( ServiceArgs_t * app_args );
    virtual ~CertServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int RSADecrypt( const cert::EncBuff & req,
        google::protobuf::BytesValue * resp );

    virtual int AESDecrypt( const cert::EncBuff & req,
        google::protobuf::BytesValue * resp );

private:
    const CertServerConfig & config_;
};

