/* logic_service_impl.cpp

 Generated by phxrpc_pb2service from logic.proto

*/

#include "logic_service_impl.h"
#include "logic_server_config.h"
#include "logic.pb.h"
#include "phxrpc/file.h"

#include "cgi_sendmsg.h"
#include "cgi_auth.h"

LogicServiceImpl :: LogicServiceImpl( ServiceArgs_t * app_args )
    : config_( *(app_args->config) )
{
}

LogicServiceImpl :: ~LogicServiceImpl()
{
}

int LogicServiceImpl :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    resp->set_value( req.value() );
    return 0;
}

int LogicServiceImpl :: Auth( const logic::MiniRequest & req,
        logic::MiniResponse * resp )
{
    CgiAuth cgi;

    return cgi.Execute( req, resp );
}

int LogicServiceImpl :: Sync( const logic::MiniRequest & req,
        logic::MiniResponse * resp )
{
    return -1;
}

int LogicServiceImpl :: SendMsg( const logic::MiniRequest & req,
        logic::MiniResponse * resp )
{
    CgiSendMsg cgi;

    return cgi.Execute( req, resp );
}


