/* logic_server_config.cpp

 Generated by phxrpc_pb2server from logic.proto

*/

#include "logic.pb.h"
#include "logic_server_config.h"

LogicServerConfig :: LogicServerConfig()
{
    enable_session_based_ = false;
}

LogicServerConfig :: ~LogicServerConfig()
{
}

bool LogicServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
            logic::MiniRequest::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    phxrpc::Config config;
    config.InitConfig( config_file );

    int tmp = 0;
    config.ReadItem( "OverloadMgr", "EnableSessionBased", &tmp, 0 );
    enable_session_based_ = ( 1 == tmp );

    phxrpc::log( LOG_ERR, "INFO: EnableSessionBased %d", enable_session_based_ ? 1 : 0 );

    return ret;
}

phxrpc::HshaServerConfig & LogicServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}

bool LogicServerConfig :: EnableSessionBased()
{
    return enable_session_based_;
}

