/* logic_tool_impl.h

 Generated by phxrpc_pb2tool from logic.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_logic_tool.h"
namespace phxrpc {
    class OptMap;
}

class LogicToolImpl : public LogicTool
{
public:
    LogicToolImpl();
    virtual ~LogicToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int Auth( phxrpc::OptMap & opt_map );

    virtual int Sync( phxrpc::OptMap & opt_map );

    virtual int SendMsg( phxrpc::OptMap & opt_map );

    virtual int FakeDoAll( phxrpc::OptMap & bigmap );
};

