/* logic_server_config.h

 Generated by phxrpc_pb2server from logic.proto

*/

#pragma once

#include "phxrpc/rpc.h"

class LogicServerConfig
{
public:
    LogicServerConfig();

    ~LogicServerConfig();

    bool Read( const char * config_file );

    phxrpc::HshaServerConfig & GetHshaServerConfig();

private:
    phxrpc::HshaServerConfig ep_server_config_;
};
