/* logic_client.h

 Generated by phxrpc_pb2client from logic.proto

*/

#pragma once

#include <string>
#include "logic.pb.h"
#include "phxrpc/rpc.h"

class LogicClient
{
public:
    LogicClient();
    ~LogicClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Auth( const logic::MiniRequest & req,
        logic::MiniResponse * resp );

    int Sync( const logic::MiniRequest & req,
        logic::MiniResponse * resp );

    int SendMsg( const logic::MiniRequest & req,
        logic::MiniResponse * resp );

    int FakeDoAll( const logic::MiniRequest & req,
        logic::MiniResponse * resp );


private:
    std::string package_name_;
    phxrpc::ClientConfig * config_;
};
