/* seq_tool_impl.h

 Generated by phxrpc_pb2tool from seq.proto

*/

#pragma once

#include <stdio.h>

#include "phxrpc_seq_tool.h"
namespace phxrpc {
    class OptMap;
}

class SeqToolImpl : public SeqTool
{
public:
    SeqToolImpl();
    virtual ~SeqToolImpl();

    virtual int PHXEcho( phxrpc::OptMap & opt_map );

    virtual int Alloc( phxrpc::OptMap & opt_map );

    virtual int Get( phxrpc::OptMap & opt_map );

};

