/* seq_service_impl.cpp

 Generated by phxrpc_pb2service from seq.proto

*/

#include "seq_service_impl.h"
#include "seq_server_config.h"
#include "seq.pb.h"
#include "phxrpc/file.h"

#include "common/redis_client_factory.h"
#include "seq_dao.h"

SeqServiceImpl :: SeqServiceImpl( ServiceArgs_t & args )
    : args_( args )
{
}

SeqServiceImpl :: ~SeqServiceImpl()
{
}

int SeqServiceImpl :: PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp )
{
    resp->set_value( req.value() );
    return 0;
}

int SeqServiceImpl :: Alloc( const seq::AllocReq & req,
        google::protobuf::UInt32Value * resp )
{
    SeqDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Alloc( req, resp );
}

int SeqServiceImpl :: Get( const google::protobuf::StringValue & req,
        seq::SyncKey * resp )
{
    SeqDAO dao( RedisClientFactory::GetDefault()->Get() );

    return dao.Get( req.value().c_str(), resp );
}

