/* seq_server_config.cpp

 Generated by phxrpc_pb2server from seq.proto

*/

#include "seq.pb.h"
#include "seq_server_config.h"

SeqServerConfig :: SeqServerConfig()
{
}

SeqServerConfig :: ~SeqServerConfig()
{
}

bool SeqServerConfig :: Read( const char * config_file )
{
    bool ret = ep_server_config_.Read( config_file );

    if ( strlen( ep_server_config_.GetPackageName() ) == 0 ) {
        ep_server_config_.SetPackageName( 
seq::AllocReq::default_instance().GetDescriptor()->file()->package().c_str() );
    }

    return ret;
}

phxrpc::HshaServerConfig & SeqServerConfig :: GetHshaServerConfig()
{
    return ep_server_config_;
}
