/* seq_client.h

 Generated by phxrpc_pb2client from seq.proto

*/

#pragma once

#include "seq.pb.h"
#include "phxrpc/rpc.h"

class SeqClient
{
public:
    static bool Init( const char * config_file );

    static const char * GetPackageName();

public:
    SeqClient();
    ~SeqClient();

    int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int PhxBatchEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    int Alloc( const seq::AllocReq & req,
        google::protobuf::UInt32Value * resp );

    int Get( const google::protobuf::StringValue & req,
        seq::SyncKey * resp );


};
