/* seq_service_impl.h

 Generated by phxrpc_pb2service from seq.proto

*/

#pragma once

#include "seq.pb.h"
#include "phxrpc_seq_service.h"

class SeqServerConfig;
class RedisClientFactory;

typedef struct tagServiceArgs {
    SeqServerConfig * config;
    //You can add other arguments here and initiate in main().
    RedisClientFactory * factory;
}ServiceArgs_t;

class SeqServiceImpl : public SeqService
{
public:
    SeqServiceImpl( ServiceArgs_t & args );
    virtual ~SeqServiceImpl();

    virtual int PHXEcho( const google::protobuf::StringValue & req,
        google::protobuf::StringValue * resp );

    virtual int Alloc( const seq::AllocReq & req,
        google::protobuf::UInt32Value * resp );

    virtual int Get( const google::protobuf::StringValue & req,
        seq::SyncKey * resp );

private:
    ServiceArgs_t & args_;
};

